# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created: Fri Mar  6 04:07:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(389, 395)
        self.gridGroupBox = QtGui.QGroupBox(Dialog)
        self.gridGroupBox.setGeometry(QtCore.QRect(9, 9, 371, 348))
        self.gridGroupBox.setBaseSize(QtCore.QSize(386, 393))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.gridGroupBox.setPalette(palette)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_15 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_15.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ktip.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("preferences_system_power_management.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setAutoRepeat(False)
        self.pushButton_15.setDefault(True)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.pushButton_15)
        self.gridLayout_2.addWidget(self.pushButton_15, 3, 0, 1, 1)
        self.pushButton_06 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_06.setText(_fromUtf8(""))
        self.pushButton_06.setIcon(icon)
        self.pushButton_06.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_06.setCheckable(True)
        self.pushButton_06.setAutoRepeat(False)
        self.pushButton_06.setDefault(True)
        self.pushButton_06.setObjectName(_fromUtf8("pushButton_06"))
        self.buttonGroup.addButton(self.pushButton_06)
        self.gridLayout_2.addWidget(self.pushButton_06, 1, 1, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_11.setText(_fromUtf8(""))
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setAutoRepeat(False)
        self.pushButton_11.setDefault(True)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.buttonGroup.addButton(self.pushButton_11)
        self.gridLayout_2.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_20.setText(_fromUtf8(""))
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setAutoRepeat(False)
        self.pushButton_20.setDefault(True)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.buttonGroup.addButton(self.pushButton_20)
        self.gridLayout_2.addWidget(self.pushButton_20, 4, 0, 1, 1)
        self.pushButton_03 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_03.setText(_fromUtf8(""))
        self.pushButton_03.setIcon(icon)
        self.pushButton_03.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_03.setCheckable(True)
        self.pushButton_03.setAutoRepeat(False)
        self.pushButton_03.setDefault(True)
        self.pushButton_03.setObjectName(_fromUtf8("pushButton_03"))
        self.buttonGroup.addButton(self.pushButton_03)
        self.gridLayout_2.addWidget(self.pushButton_03, 0, 3, 1, 1)
        self.pushButton_02 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_02.setText(_fromUtf8(""))
        self.pushButton_02.setIcon(icon)
        self.pushButton_02.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_02.setCheckable(True)
        self.pushButton_02.setAutoRepeat(False)
        self.pushButton_02.setDefault(True)
        self.pushButton_02.setObjectName(_fromUtf8("pushButton_02"))
        self.buttonGroup.addButton(self.pushButton_02)
        self.gridLayout_2.addWidget(self.pushButton_02, 0, 2, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_24.setText(_fromUtf8(""))
        self.pushButton_24.setIcon(icon)
        self.pushButton_24.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setAutoRepeat(False)
        self.pushButton_24.setDefault(True)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.buttonGroup.addButton(self.pushButton_24)
        self.gridLayout_2.addWidget(self.pushButton_24, 4, 4, 1, 1)
        self.pushButton_07 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_07.setText(_fromUtf8(""))
        self.pushButton_07.setIcon(icon)
        self.pushButton_07.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_07.setCheckable(True)
        self.pushButton_07.setAutoRepeat(False)
        self.pushButton_07.setDefault(True)
        self.pushButton_07.setObjectName(_fromUtf8("pushButton_07"))
        self.buttonGroup.addButton(self.pushButton_07)
        self.gridLayout_2.addWidget(self.pushButton_07, 1, 2, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_22.setText(_fromUtf8(""))
        self.pushButton_22.setIcon(icon)
        self.pushButton_22.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_22.setCheckable(True)
        self.pushButton_22.setAutoRepeat(False)
        self.pushButton_22.setDefault(True)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.buttonGroup.addButton(self.pushButton_22)
        self.gridLayout_2.addWidget(self.pushButton_22, 4, 2, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_17.setText(_fromUtf8(""))
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setAutoRepeat(False)
        self.pushButton_17.setDefault(True)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.buttonGroup.addButton(self.pushButton_17)
        self.gridLayout_2.addWidget(self.pushButton_17, 3, 2, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_18.setText(_fromUtf8(""))
        self.pushButton_18.setIcon(icon)
        self.pushButton_18.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setAutoRepeat(False)
        self.pushButton_18.setDefault(True)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.buttonGroup.addButton(self.pushButton_18)
        self.gridLayout_2.addWidget(self.pushButton_18, 3, 3, 1, 1)
        self.pushButton_09 = QtGui.QPushButton(self.gridGroupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_09.setPalette(palette)
        self.pushButton_09.setText(_fromUtf8(""))
        self.pushButton_09.setIcon(icon)
        self.pushButton_09.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_09.setCheckable(True)
        self.pushButton_09.setAutoRepeat(False)
        self.pushButton_09.setDefault(True)
        self.pushButton_09.setObjectName(_fromUtf8("pushButton_09"))
        self.buttonGroup.addButton(self.pushButton_09)
        self.gridLayout_2.addWidget(self.pushButton_09, 1, 4, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_13.setText(_fromUtf8(""))
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setAutoRepeat(False)
        self.pushButton_13.setDefault(True)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.buttonGroup.addButton(self.pushButton_13)
        self.gridLayout_2.addWidget(self.pushButton_13, 2, 3, 1, 1)
        self.pushButton_05 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_05.setText(_fromUtf8(""))
        self.pushButton_05.setIcon(icon)
        self.pushButton_05.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_05.setCheckable(True)
        self.pushButton_05.setAutoRepeat(False)
        self.pushButton_05.setDefault(True)
        self.pushButton_05.setObjectName(_fromUtf8("pushButton_05"))
        self.buttonGroup.addButton(self.pushButton_05)
        self.gridLayout_2.addWidget(self.pushButton_05, 1, 0, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_23.setText(_fromUtf8(""))
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setAutoRepeat(False)
        self.pushButton_23.setDefault(True)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.buttonGroup.addButton(self.pushButton_23)
        self.gridLayout_2.addWidget(self.pushButton_23, 4, 3, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_12.setText(_fromUtf8(""))
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setAutoRepeat(False)
        self.pushButton_12.setDefault(True)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.buttonGroup.addButton(self.pushButton_12)
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_16.setText(_fromUtf8(""))
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setAutoRepeat(False)
        self.pushButton_16.setDefault(True)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.buttonGroup.addButton(self.pushButton_16)
        self.gridLayout_2.addWidget(self.pushButton_16, 3, 1, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_14.setText(_fromUtf8(""))
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setAutoRepeat(False)
        self.pushButton_14.setDefault(True)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.buttonGroup.addButton(self.pushButton_14)
        self.gridLayout_2.addWidget(self.pushButton_14, 2, 4, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setAutoRepeat(False)
        self.pushButton_10.setDefault(True)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.buttonGroup.addButton(self.pushButton_10)
        self.gridLayout_2.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_08 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_08.setText(_fromUtf8(""))
        self.pushButton_08.setIcon(icon)
        self.pushButton_08.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_08.setCheckable(True)
        self.pushButton_08.setAutoRepeat(False)
        self.pushButton_08.setDefault(True)
        self.pushButton_08.setObjectName(_fromUtf8("pushButton_08"))
        self.buttonGroup.addButton(self.pushButton_08)
        self.gridLayout_2.addWidget(self.pushButton_08, 1, 3, 1, 1)
        self.pushButton_01 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_01.setText(_fromUtf8(""))
        self.pushButton_01.setIcon(icon)
        self.pushButton_01.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_01.setCheckable(True)
        self.pushButton_01.setAutoRepeat(False)
        self.pushButton_01.setDefault(True)
        self.pushButton_01.setObjectName(_fromUtf8("pushButton_01"))
        self.buttonGroup.addButton(self.pushButton_01)
        self.gridLayout_2.addWidget(self.pushButton_01, 0, 1, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_19.setText(_fromUtf8(""))
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setAutoRepeat(False)
        self.pushButton_19.setDefault(True)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.buttonGroup.addButton(self.pushButton_19)
        self.gridLayout_2.addWidget(self.pushButton_19, 3, 4, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_21.setText(_fromUtf8(""))
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setAutoRepeat(False)
        self.pushButton_21.setDefault(True)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.buttonGroup.addButton(self.pushButton_21)
        self.gridLayout_2.addWidget(self.pushButton_21, 4, 1, 1, 1)
        self.pushButton_00 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_00.setText(_fromUtf8(""))
        self.pushButton_00.setIcon(icon)
        self.pushButton_00.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_00.setCheckable(True)
        self.pushButton_00.setAutoRepeat(False)
        self.pushButton_00.setDefault(True)
        self.pushButton_00.setObjectName(_fromUtf8("pushButton_00"))
        self.buttonGroup.addButton(self.pushButton_00)
        self.gridLayout_2.addWidget(self.pushButton_00, 0, 0, 1, 1)
        self.pushButton_04 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_04.setText(_fromUtf8(""))
        self.pushButton_04.setIcon(icon)
        self.pushButton_04.setIconSize(QtCore.QSize(40, 56))
        self.pushButton_04.setCheckable(True)
        self.pushButton_04.setAutoRepeat(False)
        self.pushButton_04.setDefault(True)
        self.pushButton_04.setObjectName(_fromUtf8("pushButton_04"))
        self.buttonGroup.addButton(self.pushButton_04)
        self.gridLayout_2.addWidget(self.pushButton_04, 0, 4, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 360, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton_2.setText(_translate("Dialog", "NEW", None))

